### ISSUE TITLE
Error: Missing definition for RecoilValue

### ISSUE THREAD

**Issue by briandonahue** [facebookexperimental/Recoil#142]
Started playing around with `atomFamily` and `selectorFamily` (thanks to @tony-go's PR branch) but when trying to replace my individual `atom` and `selector` lookups with the associated family functions I am getting errors like: 
**Error: Missing definition for RecoilValue: "questionFamily__1__withFallback""**

I am assuming this is developer error, but I'm not sure what I'm doing wrong. Here is what my atomFamily looks like.  
```javascript

const questionById = buildHash() // omitting for brevity, but it's what it looks like!
const questionState = atomFamily({
  key: "questionFamily",
  default: (id) => {
    const item = questionById[id]
    return {
      type: item.type,
      label: item.label,
      value: item.value
    }
  }
});

const questionDB = {
  questionSequence: [... all question ids in sequence ],
  questionState
}

export questionDB
```

I then put this in a ReactContext to be able to get to it from other components.
```javascript
        <RecoilRoot>
          <SurveyContext.Provider value={questionDB}>
            {
              questionDB.questionSequence.map((id) => {
                return (
                  <Question  key={id}  questionId={id} />)
              })
            }
          </SurveyContext.Provider>
        </RecoilRoot>
```

Inside my Question component I have:

```javascript
const Question = (props) => {

  const questionDb = useContext(SurveyContext)
  const id = props.questionId
  const [questionState, setQuestionState] = useRecoilState(questionDb.questionState(id))

  return ( /* components */)
}
```

It's the `useRecoilState` line where the error is being thrown. Feels like I'm probably messing something up with variable scoping or by using the ReactContext to pass it around, but I'm not sure what the right way to fix it is.

**Comment by Shmew** [comment]
I had the same error, I was waiting for it to be published before I made an issue, since I wasn't sure if it was something to do with the branch or not.

**Comment by drarmstr** [comment]
cc @mondaychen

**Comment by Shmew** [comment]
I tried creating an atom whose default value was a promise which gave me an exception of `selector is not defined` when it tries to create the `atomWithFallback`. I suspect this is the root cause of this.

**Comment by drarmstr** [comment]
Should be fixed with 0.0.8

**Comment by sendittokeith** [comment]
Still getting this error when trying to use a Promise for default atom value:  "recoil": "^0.0.8",
```
recoil.development.js:200 Uncaught Error: Missing definition for RecoilValue: "undefined""
```

**Comment by jjalonso** [comment]
got this today.

selectors.js
```
export const updateUser = selector({
  key: 'updateUser',
  set: ({ get, set }, user) => {
    const allUsers = get(users);
    const userFound = allUsers[user.id];

    if (!isEqual(userFound, user)) {
      // eslint-disable-next-line no-debugger
      debugger;
      set({ ...allUsers, [user.id]: user });
    }
  },
});
```

```
Uncaught (in promise) Error: Missing definition for RecoilValue: "undefined""
    at getNode (recoil.js:381)
    at setNodeValue (recoil.js:450)
    at setRecoilState (recoil.js:4646)
    at set (selectors.js:31)
    at Object.mySet [as set] (recoil.js:4655)
    at setNodeValue (recoil.js:456)
    at applyAction (recoil.js:744)
    at recoil.js:802
    at Object.replaceState (recoil.js:1784)
    at applyActionsToStore (recoil.js:798)
    at recoil.js:821
    at Object.trace (recoil.js:151)
    at queueOrPerformStateUpdate (recoil.js:821)
    at setRecoilValue (recoil.js:864)
    at recoil.js:2569
    at Client.<anonymous> (hooks.js:37)
```
